project_id = "nbwwpadqmhmyvazxyjsb"

[functions.chat]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.bouquet-ai]
verify_jwt = false

[functions.geocode-shops]
verify_jwt = false

[functions.expire-flowers]
verify_jwt = false

[functions.generate-bouquet-image]
verify_jwt = false
